// Autogenerated from Pigeon (v2.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}



@interface FileMd5ApiCodecReader : FlutterStandardReader
@end
@implementation FileMd5ApiCodecReader
@end

@interface FileMd5ApiCodecWriter : FlutterStandardWriter
@end
@implementation FileMd5ApiCodecWriter
@end

@interface FileMd5ApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FileMd5ApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FileMd5ApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FileMd5ApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FileMd5ApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    FileMd5ApiCodecReaderWriter *readerWriter = [[FileMd5ApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void FileMd5ApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FileMd5Api> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FileMd5Api.get"
        binaryMessenger:binaryMessenger
        codec:FileMd5ApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getFilePath:error:)], @"FileMd5Api api (%@) doesn't respond to @selector(getFilePath:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_filePath = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSString *output = [api getFilePath:arg_filePath error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.FileMd5Api.getSlice"
        binaryMessenger:binaryMessenger
        codec:FileMd5ApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getSliceFilePath:error:)], @"FileMd5Api api (%@) doesn't respond to @selector(getSliceFilePath:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_filePath = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSString *output = [api getSliceFilePath:arg_filePath error:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
