// Autogenerated from Pigeon (v2.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FileMd5Api.
NSObject<FlutterMessageCodec> *FileMd5ApiGetCodec(void);

@protocol FileMd5Api
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getFilePath:(NSString *)filePath error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getSliceFilePath:(NSString *)filePath error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FileMd5ApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FileMd5Api> *_Nullable api);

NS_ASSUME_NONNULL_END
